name: update

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out my other private repo
        uses: actions/checkout@main
        with:
          repository: nsidc/CIRRUS-core
          token: ${{ secrets.GH_PAT_DEPS_TOKEN }}
      - run: ./update.sh
